### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by PouyaGh** [fanyangxyz/Neural-LP#1]
I tried to run the code as the readme suggested. I got the following error:

Traceback (most recent call last):
  File "src/main.py", line 6, in <module>
    from model import Learner
  File "~/Neural-LP-master/src/model.py", line 207
    lambda (grad, var): self._clip_if_not_None(grad, var, -5., 5.), gvs) 
           ^
SyntaxError: invalid syntax

**Comment by fanyangxyz** [comment]
Hi, I ran the code using the command in README, but I can't reproduce the syntax error you showed. Did you use Python 2.7?

**Comment by PouyaGh** [comment]
Thanks for your response, I used a cluster and on the cluster the Python 3.5.4 is available. You right that might be the cause.
