### ISSUE TITLE
u_{T+1}: Final step in the recurrent formulation

### ISSUE THREAD

**Issue by ajaynagesh** [fanyangxyz/Neural-LP#10]
@fanyangxyz : In the code starting at:  https://github.com/fanyangxyz/Neural-LP/blob/cbb6a9d14ad28f33cd37050c45e6b01ceb2d47d5/src/model.py#L148, I do not see the final step in the recurrent formulation, namely, Eq 8 in your NIPS paper. 

I am a little confused in this part. Could you please explain ? 

Further, I assume https://github.com/fanyangxyz/Neural-LP/blob/master/src/model.py#L149 is Eq 11 in the paper. However, the indices seem to not match the equation. In the equation, you have `softmax([h_0 .. h_{t-1}]^T h_t)` but the code seems to suggest `softmax([h_0 .. h_{t}]^T h_t)`

It would be really great if you could explain this discrepancy. Thanks

**Comment by fanyangxyz** [comment]
num_step is equal to max_rule_len+1

**Comment by ajaynagesh** [comment]
Thanks!
