### ISSUE TITLE
Other datasets / experimental framework

### ISSUE THREAD

**Issue by ajaynagesh** [fanyangxyz/Neural-LP#11]
@fanyangxyz Do you plan to release the other datasets and the experimental framework of the NIPS 2017 paper ? It would be very helpful for research purposes. 

Thanks!

**Comment by fanyangxyz** [comment]
Hi @ajaynagesh the datasets are all publicly available online. Could you be more specific about what "experimental framework" is?

**Comment by ajaynagesh** [comment]
Hi @fanyangxyz : Thanks for your response! I was looking at the datasets mentioned in the paper in the  following repos: https://github.com/shehzaadzd/MINERVA, https://github.com/uclmr/ntp. 

I saw some discrepancies in the numbers mentioned in your paper and those datasets. For instance, in the UMLS dataset, you mention 46 relations, but I observed 96 relations. 

Also the number of training examples and facts in the FB-237 dataset also seems to be a little off (although in the same ballpark). 

I was wondering if you used a subset/filtered version of these datasets. (since you also mention that you split the data into facts, train and test in 6:2:1) 

Thanks!

**Comment by fanyangxyz** [comment]
I uploaded the preprocessed fb15k-237 data to the repo. This is what we used in the experiment. The README there should explain why the numbers are different, i.e. the original train file is partitioned into facts.txt and train.txt. You can preprocess the other datasets similarly. I'll also try to upload more preprocessed data and related scripts. Stay tuned.

**Comment by ajaynagesh** [comment]
Thanks!

**Comment by ajaynagesh** [comment]
Hi @fanyangxyz  I was trying to run your system on the FB15k-237 dataset. I am maxing out of GPU memory. I have a 3-core Tesla P4 with around 7.6G memory on each. Do you happen to know the hardware configuration of the machine you ran these experiments on ? Is there a way, you suggest to circumvent the memory issue ? Thanks once again for making the datasets available!

**Comment by fanyangxyz** [comment]
I ran the experiments on a GPU with 12 GB RAM. I don't think the current implementation is distributed (i.e. use multiple GPUs). To circumvent the OOM issue, maybe you can first try decrease the model size, e.g. decrease the hidden dimension size.
