### ISSUE TITLE
Small edits to instructions mentioned 

### ISSUE THREAD

**Issue by arsenious** [fanyangxyz/Neural-LP#14]
Hi

Thank you for this code.

I think these edits would help people running the code:

.eval/collect_all_facts.**sh** datasets/family
python eval/get_truths.py datasets/family
python eval/evaluate.py --preds=exps/**family**/test_predictions.py --truths=datasets/family/truths.pckl

**Comment by fanyangxyz** [comment]
Thanks for the note! The README is updated.
