### ISSUE TITLE
Do you think Neural-LP can solve this kind of question?

### ISSUE THREAD

**Issue by guotong1988** [fanyangxyz/Neural-LP#2]
1,
A lives in C. `(A, liveInCity, C)`
B lives in C. `(B, liveInCity, C)`
Does A and B live in the same city?

2,
A is 180 cm height. `(A, height, 180)`
B is 175 cm height. `(B, height, 175)`
Is B taller than A?

Thank you very much.@fanyangxyz

**Comment by fanyangxyz** [comment]
Hi, 
I don't think Neural-LP can solve such questions right now, mainly because it seems difficult to write a chain-like logical program to answer the questions. Though it also depends on how the knowledge base looks like, i.e. what relations are available.

**Comment by guotong1988** [comment]
Thank you for your reply. Based on your knowledge, do you know what kind of models can solve this kind of questions? Thank you~

**Comment by fanyangxyz** [comment]
Maybe semantic parsing related works can help.

**Comment by guotong1988** [comment]
I also guess semantic parsing is the solution.:)

**Comment by guotong1988** [comment]
But do you think a graph with more information can do it? 
In other words, add more information into the graph.

**Comment by guotong1988** [comment]
I am thinking that, if KG-walk can solve all the problem, then we can give up semantic parsing.
What do you think?

**Comment by fanyangxyz** [comment]
If the information in the KG is complete, than inference/reasoning/semantic parsing becomes very simple.
