### ISSUE TITLE
Could you please teach me what the alpha and beta of the paper correspond to the code?

### ISSUE THREAD

**Issue by guotong1988** [fanyangxyz/Neural-LP#3]
What are α and β of the paper in the code?
I guess they may be in [src/model.py](https://github.com/fanyangxyz/Neural-LP/blob/master/src/model.py)

Thank you.
Thank you.
Thank you.
@fanyangxyz

**Comment by fanyangxyz** [comment]
Algorithm 1 in the paper explains how α and β can be derived from the attentions.
