### ISSUE TITLE
Could not understand these lines of code, Thank you..

### ISSUE THREAD

**Issue by guotong1988** [fanyangxyz/Neural-LP#5]
https://github.com/fanyangxyz/Neural-LP/blob/master/src/model.py#L213-L214

```
feed[self.queries] = [[q] * (self.num_step-1) + [self.num_query] for q in qq]
```
Why use many copy of `q`?
Thank you @fanyangxyz

**Comment by guotong1988** [comment]
I guess `+ [self.num_query] ` is the 'special END token'.

**Comment by cao-nv** [comment]
I have the same question with goutong1988 😀  
I can not figure out how the query is fed to RNN.

**Comment by fanyangxyz** [comment]
The same query is fed to the RNN at each step. This is why we use many copies of q. See also Sec 3.3. in the paper.
