### ISSUE TITLE
Why we need both query and M?

### ISSUE THREAD

**Issue by guotong1988** [fanyangxyz/Neural-LP#8]
We want to predict the probability over all the M.
What is the function of `query` as place_holder input.
Thank you.
@fanyangxyz

**Comment by fanyangxyz** [comment]
I don't quite understand the question. Can you elaborate?

**Comment by guotong1988** [comment]
Thank you!
`query` is the ground truth?
Am I right?

**Comment by fanyangxyz** [comment]
What do you mean by "ground truth"?

**Comment by guotong1988** [comment]
Thank you!
I am not sure. So I can not answer. But,
Could you explain, in this task, what are the inputs of the model and what are the targets of the model?

**Comment by fanyangxyz** [comment]
Please see the paper for details about the model.
