### ISSUE TITLE
Negative facts coverage

### ISSUE THREAD

**Issue by NSanjay** [fanyangxyz/Neural-LP#9]
Hi @fanyangxyz ,

Can Neural-LP be modelled to generate the set of rules in the presence of incorrect and negative facts in the database? Basically, the rules should cover as many facts as possible from the positive (facts.txt) and as little negatives as possible from a negatives.txt

**Comment by fanyangxyz** [comment]
Hi @NSanjay 

Currently we do not consider the case where there are incorrect or negative facts. This is a very interesting and important direction to explore.
